/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CollapeData: typeof import('./src/components/Collapse/CollapeData.vue')['default']
    CollapeFilter: typeof import('./src/components/Collapse/CollapeFilter.vue')['default']
    CollapseDrawLayer: typeof import('./src/components/Collapse/CollapseDrawLayer.vue')['default']
    CollapseStyleLayer: typeof import('./src/components/Collapse/CollapseStyleLayer.vue')['default']
    ContentMap: typeof import('./src/components/Content/ContentMap.vue')['default']
    ContentSide: typeof import('./src/components/Content/ContentSide.vue')['default']
    Editor: typeof import('./src/components/Editor.vue')['default']
    FormMapDraw: typeof import('./src/components/Form/FormMapDraw.vue')['default']
    ModalDataMultipleMarker: typeof import('./src/components/Modal/ModalDataMultipleMarker.vue')['default']
    ModalDrawDataUpload: typeof import('./src/components/Modal/ModalDrawDataUpload.vue')['default']
    ModalMapDraw: typeof import('./src/components/Modal/ModalMapDraw.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabPanelIconBtn: typeof import('./src/components/TabPanel/TabPanelIconBtn.vue')['default']
    TabPanelMenu: typeof import('./src/components/TabPanel/TabPanelMenu.vue')['default']
  }
}
